### ISSUE TITLE
PDU wrong link ?

### ISSUE THREAD

**Issue by aharivel** [christianhorn/smallhelpers#1]
Hi Christian,

Very interesting research ! 
I  need to test pmda-denki for sure.

Just a little hiccups here, no? That doesn't look like a PDU in the link 

https://github.com/christianhorn/smallhelpers/blob/d1614aab2750aa866bc4f6c9839930597e7a99d6/pmda-denki-handbook/denki.html#L966

Best regards,
Anthony

**Comment by christianhorn** [comment]
Thanks, Anthony!
I've clarified this piece, more details on the PDU here and the link - the link is to Sushy, a python library, which supports redfish and a colleague successfully used that combination.
